main.py
from flask import Flask, url_for, render_template
from routes.home import home_route
from routes.cliente import cliente_route

app = Flask(__name__)

app.register_blueprint(home_route)
app.register_blueprint(cliente_route, url_prefix='/clientes')

app.run(debug=True)

routes/cliente.py
from flask import Blueprint, render_template, request
from  database.cliente import CLIENTES


cliente_route = Blueprint('cliente', __name__)

@cliente_route.route('/')
def listar_clientes():
       """ lista os clients """
       return render_template('lista_clientes.html', clientes=CLIENTES)


@cliente_route.route('/', methods=['POST'])
def inserir_cliente( ):      
       """ inserir um cliente os dados"""
       
       data = request.json
       
       novo_usuario = {
              "id": len(CLIENTES) + 1,
              "nome": data['nome'],
              "email": data['email'],
       }
       
       CLIENTES.append(novo_usuario)
       
       return render_template('item_cliente.html', cliente=novo_usuario)


@cliente_route.route('/new')
def form_cliente( ):
       """ Formulario para cadastrar um cliente """
       return render_template('form_cliente.html')



@cliente_route.route('/<int:cliente_id>')
def detalhe_cliente(cliente_id):
       """ obter dados de 1 cliente """
       return render_template('detalhe_cliente.html')



@cliente_route.route('/<int:cliente_id>/edit')
def form_edit_cliente(cliente_id):
       """ editar um cliente """
       
       cliente = None
       for  c in CLIENTES:
              if c ['id'] == cliente_id:
                     cliente = c
       
       return render_template('form_cliente.html', cliente=cliente)


@cliente_route.route('/<int:cliente_id>/update', methods=['PUT'])
def atualizar_cliente(cliente_id):
       """ atualizar dados de 1 cliente """
       cliente_editado = None
       # obter dados formulario edicao
       data = request.json 
       # obter usuario pelo id
       for c in CLIENTES:
              if c ['id'] == cliente_id:
                     c['nome'] = data['nome']
                     c['email'] = data['email']
                     
                     cliente_editado = c
       # editar usuario
       
       return render_template('item_cliente.html', cliente=cliente_editado)


@cliente_route.route('/<int:cliente_id>/delete', methods=['DELETE'])
def deletar_cliente(cliente_id):
       global CLIENTES
       
       CLIENTES = [ c for c in CLIENTES if c['id'] != cliente_id ]
       return {'deleted': 'ok'}

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
       return render_template('index.html')

templates/form_cliente.html
<form class="c-form"{% if cliente %}action="{{ url_for('cliente.atualizar_cliente', cliente_id=cliente.id) }}"{% else %}action="{{ url_for('cliente.inserir_cliente') }}"{% endif %} 

        method=" {% if cliente %}PUT{% else %}POST{% endif %}"

        {% if cliente %}
            c-swap="#clinete-{{cliente.id}}"
        {% else %}
            c-append="#lista-clientes"
        {% endif %}

         >
       <div class="mb-3">
         <label class="form-label">Nome</label>
         <input type="text" class="form-control" name="nome" {% if cliente %}value="{{cliente.nome}}"{% endif %}>
       </div>


       <div class="mb-3">
              <label id="label-target" class="form-label">Email</label>
              <input type="text" class="form-control" name="email" {% if cliente %}value="{{cliente.email}}"{% endif %}>
       </div>

       <button type="submit" class="btn btn-primary">{% if cliente %} Salvar {% else %} Criar {% endif %}</button>
</form>

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
  </head>
  <body>

    <div class="container">

      <h1 class="text-center">Gestão de Clientes</h1>

      <!-- Formulário add cliente -->
      <div id="form-cliente" c-container="{{ url_for('cliente.form_cliente') }}"></div>


      <hr>

      <!-- Lista de cliente -->
      <h2>Lista de clientes</h2>
      <div c-container="{{ url_for('cliente.listar_clientes') }}"></div>
      
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/cru.js') }}"></script>
  </body>
</html>

templates/item_cliente.html
<tr id="cliente-{{ cliente.id }}">
       <th scope="row">{{ cliente.id }}</th>
       <td>{{ cliente.nome }}</td>
       <td>{{ cliente.email }}</td>
       <td>
              <button class="btn btn-primary"
                      c-get="{{ url_for('cliente.form_edit_cliente', cliente_id=cliente.id) }}"
                      c-target="#form-cliente"
                      >
                      Editar
                     </button>
              <button class="btn btn-danger" 
                      c-delete="{{ url_for('cliente.deletar_cliente', cliente_id=cliente.id ) }}"
                      c-remove-closest="tr">
                      Deletar
              </button>
       </td>
</tr>

templates/lista_clientes.html
<table class="table">
       <thead>
         <tr>
           <th scope="col">#</th>
           <th scope="col">Nome</th>
           <th scope="col">Email</th>
           <th scope="col">Ações</th>
         </tr>
       </thead>
       <tbody id="lista-clientes">

              {% for cliente in clientes %}
                     {% include 'item_cliente.html' %}
              {% endfor %}


       </tbody>
     </table>